SELECT USER_ID, Min(c_amount) >=10, Min(CREATED_DATE)
FROM transactions, fx_rates
WHERE TYPE = 'CARD_PAYMENT' AND STATE = 'COMPLETED' AND CURRENCY = ccy AND base_ccy = 'USD' AND (AMOUNT * rate) >= 10 AS c_amount
GROUP BY USER_ID;



SELECT USER_ID
FROM transactions, fx_rates
WHERE TYPE = 'CARD_PAYMENT' AND STATE = 'COMPLETED' AND CURRENCY = ccy AND base_ccy = 'USD'
GROUP BY USER_ID
HAVING (AMOUNT * rate) >= 10 AND Min(CREATED_DATE);


SELECT USER_ID, Min(AMOUNT * rate), AMOUNT, CREATED_DATE
FROM transactions, fx_rates
WHERE TYPE = 'CARD_PAYMENT' AND STATE = 'COMPLETED' AND CURRENCY = ccy AND base_ccy = 'USD'
GROUP BY USER_ID
HAVING (AMOUNT * rate) >= 10 AND Min(CREATED_DATE);


SELECT Min(CREATED_DATE) as first_transaction, USER_ID
FROM transactions 
GROUP by USER_ID;


SELECT CREATED_DATE, USER_ID
FROM transactions 
GROUP by USER_ID
HAVING Min(CREATED_DATE) AND USER_ID = (SELECT USER_ID FROM transactions, fx_rates WHERE TYPE = 'CARD_PAYMENT' AND STATE = 'COMPLETED' AND CURRENCY = ccy AND base_ccy = 'USD' AND (AMOUNT * rate) >= 10);

WITH ft AS (SELECT Min(CREATED_DATE), USER_ID
FROM transactions 
GROUP by USER_ID)
SELECT USER_ID,
FROM transactions, ft
WHERE USER_ID=ft.USER_ID;

WITH ft as (SELECT Min(CREATED_DATE), USER_ID
FROM transactions
GROUP by USER_ID)
SELECT USER_ID,
FROM ft;


SELECT USER_ID, (AMOUNT * rate)
FROM (SELECT Min(CREATED_DATE), USER_ID, TYPE, STATE, CURRENCY, AMOUNT
FROM transactions 
GROUP by USER_ID), fx_rates
WHERE TYPE = 'CARD_PAYMENT' AND STATE = 'COMPLETED' AND CURRENCY = ccy AND base_ccy = 'USD' AND (AMOUNT * rate) >= 10;